import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ToastProvider } from '@/components/ui/ToastProvider';
import StoreProvider from '@/providers/storeProvider';
import SideNav from "@/components/SideNav";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ToastProvider>
            <div className="min-h-screen w-full bg-[#0A0F1A] text-slate-100 flex flex-col md:flex-row">
              <SideNav />
              <main className="flex-1">{children}</main>
            </div>
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
